### ISSUE TITLE
How to stack the function inside a pipeline?

### ISSUE THREAD

**Issue by bruAristimunha** [Roche/neuro-meeglet#1]
Hi @dengemann!

Suuuper beautiful library and super refreshing documentation! Like everything you produce, the text, explanation, and layout are excellent! 

I was studying all the documentation, and a question arose: how do you recommend using wavelet generation for a pipeline object?

In your biomarker paper, you use the steps:
- Wavelet convolution
- Cov
- Vectorization
- [Upper, SPoC, ...] (clf head)

I understand that this library generates the Wavelet convolution step, so the intuition would be to use something like this:

```python
def compute_wavelet_convolution(raw: mne.Raw):
  out, info = compute_spectral_features(
       raw, foi_start=1, foi_end=32, bw_oct=0.25, delta_oct=1,
       density='oct', features='cov_oas')
   return out

from sklearn.preprocessing import FunctionTransformer
from sklearn.pipeline import Pipeline

first_step = FunctionTransformer(func=compute_wavelet_convolution)

pipe = Pipeline([("wavelet", first_step)])

```

Am I understanding the intuition on how to use it correctly?

**Comment by dengemann** [comment]
Thank you @bruAristimunha ! I would kindly ask you for further patience. More documentation will be added. Of note, this library does not include the research code from the Bomatter preprint, which is a separate item.
